<!DOCTYPE html>
<html>
<head>
    <title>Two-Factor Authentication Setup</title>
</head>
<body>
    <h1>Set up Two-Factor Authentication</h1>

    <p>Scan this QR code with your authenticator app (Google Authenticator, Authy, etc.):</p>

    <div>
        {!! $qrCodeSvg !!}
    </div>

    <p>Then enter the code generated by your app to confirm setup:</p>

    <form method="POST" action="{{ route('2fa.setup.post') }}">
        @csrf
        <input type="text" name="code" placeholder="Enter authentication code" autofocus autocomplete="one-time-code" required>
        <button type="submit">Enable 2FA</button>
    </form>

    @if ($errors->any())
        <div style="color:red;">
            @foreach ($errors->all() as $error)
                <div>{{ $error }}</div>
            @endforeach
        </div>
    @endif

</body>
</html>
